# Generated by Django 5.1.1 on 2025-05-12 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='comments',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comment'),
        ),
    ]
